# Auto-generated by generate_sitewise_tf.py
# Do not edit manually — changes will be overwritten

resource "awscc_iotsitewise_asset_model" "mixingedgetoplatform" {
  asset_model_name = "MixingEdgeToPlatform"

  asset_model_properties = [
    {
      name      = "EdgeData/ProcessValues/BatchCount"
      data_type = "INTEGER"
      type = {
        measurement = {}
      }
    },
    {
      name      = "EdgeData/ProcessValues/FlowRate"
      data_type = "DOUBLE"
      type = {
        measurement = {}
      }
    },
    {
      name      = "EdgeData/ProcessValues/MotorCurrent"
      data_type = "DOUBLE"
      type = {
        measurement = {}
      }
    },
    {
      name      = "EdgeData/ProcessValues/Pressure"
      data_type = "DOUBLE"
      type = {
        measurement = {}
      }
    },
    {
      name      = "EdgeData/ProcessValues/RotationSpeed"
      data_type = "DOUBLE"
      type = {
        measurement = {}
      }
    },
    {
      name      = "EdgeData/ProcessValues/Temperature"
      data_type = "DOUBLE"
      type = {
        measurement = {}
      }
    },
    {
      name      = "EdgeData/ProcessValues/TorqueOutput"
      data_type = "DOUBLE"
      type = {
        measurement = {}
      }
    },
    {
      name      = "EdgeData/ProcessValues/Vibration"
      data_type = "DOUBLE"
      type = {
        measurement = {}
      }
    },
    {
      name      = "EquipmentInfo/MachineCode"
      data_type = "STRING"
      type = {
        measurement = {}
      }
    },
    {
      name      = "EquipmentInfo/Manufacturer"
      data_type = "STRING"
      type = {
        measurement = {}
      }
    },
  ]
}
