# Auto-generated by generate_sitewise_tf.py
# Do not edit manually — changes will be overwritten

resource "awscc_iotsitewise_asset_model" "trayhandleredgetoplatform" {
  asset_model_name = "TrayHandlerEdgeToPlatform"

  asset_model_properties = [
    {
      name      = "EdgeData/ProductionData/CycleTime"
      data_type = "DOUBLE"
      type = {
        measurement = {}
      }
    },
    {
      name      = "EdgeData/ProductionData/GoodPartsCounter"
      data_type = "INTEGER"
      type = {
        measurement = {}
      }
    },
    {
      name      = "EdgeData/ProductionData/OperationMode"
      data_type = "INTEGER"
      type = {
        measurement = {}
      }
    },
    {
      name      = "EdgeData/ProductionData/RejectedPartsCounter"
      data_type = "INTEGER"
      type = {
        measurement = {}
      }
    },
    {
      name      = "EquipmentInfo/Description"
      data_type = "STRING"
      type = {
        measurement = {}
      }
    },
    {
      name      = "EquipmentInfo/MachineCode"
      data_type = "STRING"
      type = {
        measurement = {}
      }
    },
    {
      name      = "EquipmentInfo/Manufacturer"
      data_type = "STRING"
      type = {
        measurement = {}
      }
    },
  ]
}
