# Auto-generated by generate_sitewise_tf.py
# Do not edit manually — changes will be overwritten
# Site: waterford

resource "awscc_iotsitewise_asset" "waterford_fillingline1" {
  asset_name     = "waterford/FillingLine1"
  asset_model_id = "" # TODO: reference deployed model ID
}

resource "awscc_iotsitewise_asset" "waterford_fillingline2" {
  asset_name     = "waterford/FillingLine2"
  asset_model_id = "" # TODO: reference deployed model ID
}

resource "awscc_iotsitewise_asset" "waterford_fillingline3" {
  asset_name     = "waterford/FillingLine3"
  asset_model_id = "" # TODO: reference deployed model ID
}

resource "awscc_iotsitewise_asset" "waterford_fillingline4" {
  asset_name     = "waterford/FillingLine4"
  asset_model_id = "" # TODO: reference deployed model ID
}

resource "awscc_iotsitewise_asset" "waterford_fillingline5" {
  asset_name     = "waterford/FillingLine5"
  asset_model_id = "" # TODO: reference deployed model ID
}
