# Auto-generated by generate_sitewise_tf.py
# Do not edit manually — changes will be overwritten
# Site: waterford

resource "awscc_iotsitewise_asset" "waterford_packagingline1" {
  asset_name     = "waterford/PackagingLine1"
  asset_model_id = "" # TODO: reference deployed model ID
}
