# Auto-generated by generate_sitewise_tf.py
# Do not edit manually — changes will be overwritten
# Site: waterford

resource "awscc_iotsitewise_asset" "waterford_packagingline3" {
  asset_name     = "waterford/PackagingLine3"
  asset_model_id = "" # TODO: reference deployed model ID
}

resource "awscc_iotsitewise_asset" "waterford_packagingline2" {
  asset_name     = "waterford/PackagingLine2"
  asset_model_id = "" # TODO: reference deployed model ID
}
