# Auto-generated by generate_sitewise_tf.py
# Do not edit manually — changes will be overwritten
# Site: dublin

resource "awscc_iotsitewise_asset" "dublin_fillingmachine1" {
  asset_name     = "dublin/FillingMachine1"
  asset_model_id = "" # TODO: reference deployed model ID
}

resource "awscc_iotsitewise_asset" "dublin_fillingmachine2" {
  asset_name     = "dublin/FillingMachine2"
  asset_model_id = "" # TODO: reference deployed model ID
}
