# Auto-generated by generate_sitewise_tf.py
# Do not edit manually — changes will be overwritten
# Site: dublin

resource "awscc_iotsitewise_asset" "dublin_packagingline1" {
  asset_name     = "dublin/PackagingLine1"
  asset_model_id = "" # TODO: reference deployed model ID
}

resource "awscc_iotsitewise_asset" "dublin_packagingline2" {
  asset_name     = "dublin/PackagingLine2"
  asset_model_id = "" # TODO: reference deployed model ID
}

resource "awscc_iotsitewise_asset" "dublin_packagingline3" {
  asset_name     = "dublin/PackagingLine3"
  asset_model_id = "" # TODO: reference deployed model ID
}

resource "awscc_iotsitewise_asset" "dublin_packagingline4" {
  asset_name     = "dublin/PackagingLine4"
  asset_model_id = "" # TODO: reference deployed model ID
}
