# Auto-generated by generate_sitewise_tf.py
# Do not edit manually — changes will be overwritten
# Site: WAT

resource "awscc_iotsitewise_asset" "wat_mixingunit001" {
  asset_name     = "WAT/MixingUnit001"
  asset_model_id = "" # TODO: reference deployed model ID

  asset_properties = [
    {
      alias      = "/EdgeData/ProcessValues/Pressure"
      logical_id = "edgedata_processvalues_pressure_property"
    },
    {
      alias      = "/EdgeData/ProcessValues/RotationSpeed"
      logical_id = "edgedata_processvalues_rotationspeed_property"
    },
    {
      alias      = "/EdgeData/ProcessValues/Temperature"
      logical_id = "edgedata_processvalues_temperature_property"
    },
  ]
}

resource "awscc_iotsitewise_asset" "wat_fillingline002" {
  asset_name     = "WAT/FillingLine002"
  asset_model_id = "" # TODO: reference deployed model ID

  asset_properties = [
    {
      alias      = "/EdgeData/ProductionData/BatchNumber"
      logical_id = "edgedata_productiondata_batchnumber_property"
    },
    {
      alias      = "/EdgeData/ProductionData/GoodPartsCounter"
      logical_id = "edgedata_productiondata_goodpartscounter_property"
    },
    {
      alias      = "/EdgeData/ProductionData/RejectCounter"
      logical_id = "edgedata_productiondata_rejectcounter_property"
    },
  ]
}
